// s2/plugins/vue/S2Map.vue
<template>
  <div id="map" ref="container">
    <slot />
  </div>
</template>

<script lang="ts">
import { preloadMap } from '../preload.js';
import { onMounted, onUnmounted, ref, shallowRef, toRaw } from 'vue';

import { BuildType } from '../preload.js';
import type { MapOptions, S2Map } from 's2/index.js';
import type { PropType, Ref } from 'vue';

/** The exported container and mapInstance */
export interface S2MapComponent {
  container: Ref<HTMLElement | undefined>;
  mapInstance: Ref<S2Map | null>;
}

export default {
  name: 'S2MapGPU',
  props: {
    mapOptions: {
      type: Object as PropType<MapOptions>,
      required: true,
    },
    mapReady: {
      type: Function as PropType<(s2map: S2Map) => void>,
      required: false,
      default: undefined,
    },
    build: {
      type: String as PropType<BuildType>,
      required: true,
    },
    version: {
      type: String as PropType<string>,
      required: false,
      default: 'latest',
    },
    testing: {
      type: Boolean as PropType<boolean>,
      required: false,
      default: false,
    },
  },
  /**
   * Setup the component, map instance, and mounting/unmounting config
   * @param props - Props passed to the component
   * @returns container and mapInstance
   */
  setup(props): S2MapComponent {
    let { mapOptions, mapReady, build, version, testing } = props;
    mapOptions = toRaw(mapOptions);
    const container = ref<HTMLElement>();
    const mapInstance = shallowRef<S2Map | null>(null);

    onMounted(async () => {
      await preloadMap(build, version);
      const S2Map = window.S2Map;
      const options: MapOptions = {
        ...mapOptions,
        container: container.value,
      };
      const map = new S2Map(options);
      if (testing === true) window.testMap = map;

      if (typeof mapReady === 'function')
        map.addEventListener(
          'ready',
          () => {
            mapReady(map);
          },
          { once: true },
        );

      mapInstance.value = map;
    });

    onUnmounted(() => {
      if (mapInstance.value !== null) mapInstance.value.delete();
    });

    return { container, mapInstance };
  },
};
</script>

<style scoped>
#map {
  position: absolute;
  top: 0;
  bottom: 0;
  width: 100%;
  height: 100%;
}
</style>

// frameworks/react/S2Map.tsx
import { BuildType, preloadMap } from '../preload';
import React, { useEffect, useRef, useState } from 'react';

import type { MapOptions, S2Map } from 's2/index';

/**
 * Props for the S2Map React Component.
 * Props are:
 * - `build`: The build type for the S2Map instance. See {@link BuildType}.
 * - `mapOptions`: The options for the S2Map instance.
 * - `mapReady?`: A function to be called when the S2Map instance is ready. Optional
 * - `version?`: The version of the S2Map instance. Optional
 * - `children?`: Child elements to be rendered inside the S2Map instance. Optional
 */
export interface S2MapReactComponentProps {
  build: BuildType;
  mapOptions: MapOptions;
  mapReady?: (s2map: S2Map) => void;
  version?: string;
  children?: React.ReactNode;
  testing?: boolean;
}

/**
 * S2Map React Component
 * @param props - Props passed to the component
 * @returns - The S2Map React Component
 */
export const ReactS2MapGPU: React.FC<S2MapReactComponentProps> = (
  props: S2MapReactComponentProps,
) => {
  const { mapOptions, mapReady, build, version, children, testing } = props;
  const containerRef = useRef<HTMLDivElement | null>(null);
  const [mapInstance, setMapInstance] = useState<S2Map | null>(null);

  useEffect(() => {
    let map: S2Map | null = null;

    /** Initialize the map */
    const initializeMap = async () => {
      await preloadMap(build, version);
      const S2Map = window.S2Map; // Assuming S2Map is available globally after preload

      if (containerRef.current !== null) {
        const options: MapOptions = {
          ...mapOptions,
          container: containerRef.current,
        };
        map = new S2Map(options);
        if (testing === true) window.testMap = map;
        setMapInstance(map);

        if (typeof mapReady === 'function') {
          map.addEventListener(
            'ready',
            () => {
              mapReady(map!); // Assert map is not null here as it's just been created
            },
            { once: true },
          );
        }
      }
    };

    void initializeMap();

    return () => {
      if (mapInstance !== null) mapInstance.delete();
    };
  }, [mapOptions, mapReady, build, version]);

  return (
    <div
      id="map"
      ref={containerRef}
      style={{ position: 'absolute', top: 0, bottom: 0, width: '100%', height: '100%' }}
    >
      {children}
    </div>
  );
};
